export const coachImages: Record<string, string> = {
  "Rebecca Amisano": "/images/coaches/rebecca-amisano_new.jpg",
  "Archie Wolifson": "/images/coaches/archie-wolifson.jpg",
  "Timothy Hanna": "/images/coaches/timothy-hanna.jpg",
  "Gabrielle Wong": "/images/coaches/gabrielle-wong.jpg",
  "Rose Oh": "/images/coaches/rose-oh.jpg",
  "Serina Guo": "/images/coaches/serina-guo.jpg",
  "Finn Liu": "/images/coaches/finn-liu.jpg",
  "Emily Cui": "/images/coaches/emily-cui.jpg",
  "Catherine Wong": "/images/coaches/catherine-wong.jpg",
  "Anisha Biswas": "/images/coaches/anisha-biswas.jpg",
  "Akash Krishnamurthy": "/images/coaches/akash_headshot.jpeg",
  "Annika Wang": "/images/coaches/wang_annika.jpg",
  "Ming Su": "/images/coaches/su_ming.jpg",
  "Angela Meng": "/images/coaches/meng_angela.jpg",
  "Kevin Nan": "/images/coaches/nan_kevin.jpg",
  "Ethan Curry": "/images/coaches/ethan-curry.jpg",
  "David Zu": "/images/coaches/david-zu.jpg",
  "Ten Watanaprakarnchai": "/images/coaches/ten-watanaprakarnchai.jpg",
  "Jessie Zhang": "/images/coaches/jessie-zhang.jpg",
};
